### ISSUE TITLE
Table is not registered with a Database. Did you forget the @Table annotation?

### ISSUE THREAD

**Issue by levibostian** [Raizlabs/DBFlow#745]
Hello. 

I'm trying to use DBFlow version 3.0.0-beta5 in a project that uses
- Dagger 2.2
- DBFlow v3.0.0-beta5
- Glide v3.7.0
- Retrofit v2.0.0
- Couple other small libraries for small utility stuff like AndroidViewAnimations. 

I often times get the following exception:

```
com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Table: com.levibostian.app.UserModel is not registered with a Database. Did you forget the @Table annotation?
```

This is not consistent, but happens very often, cleaning and rebuilding the app usually doesn't help (but sometimes does).

I have checked out [this issue](https://github.com/Raizlabs/DBFlow/issues/515) which talks about disabling instant run, which I have done with same result of it happening most of the time, but not every single time. 

I have also checked out [this issue](https://github.com/Raizlabs/DBFlow/issues/685) which talks about using `gradle clean` from command line instead of in Android Studio. I have been doing `./gradlew clean` and reinstalling my app every build (even if I do not edit any of the DBFlow touching code in my project) and no change of behavior either. 

Like I mentioned before, I am receiving this regularly but not every time. Maybe 75% of the time? The stacktrace triggers on this line of code:

```
mFlowCursorList = new FlowCursorList<UserModel>(false, SQLite.select().from(UserModel.class).where(UserModel_Table.responded.isNull()).orderBy(UserModel_Table.user_id, true));
```

in my adapter class which may be the first part of interaction with my Model classes. When the app does run the 25% of the time, it runs great with no issues. 

Any help, please and thank you.

**Comment by levibostian** [comment]
I have more info. 

1. This is not because of Dagger. I have an app I am working on with DBFlow and no other dependencies besides Fabric.io and the support libraries. 
2. This is not because of Android Studio 2.0 and/or the Gradle v2.0 plugin. I reverted back to v1.5 with the same app and still no luck. 

Still getting error about 40% of the time. Then it requires me to clean the project and recompile where it again, 40% of the time works.

**Comment by agrosner** [comment]
Have you checked out the generated code to see if it can provide any clues?

**Comment by mathieudebrito** [comment]
+1 !
I'm also using Android Annotations.
But I thing the code is well generated : 

```
public final class DbFlowDatabaseMyProjectDbFlowDatabaseV8$Database extends BaseDatabaseDefinition {
  public DbFlowDatabaseMyProjectDbFlowDatabaseV8$Database(DatabaseHolder holder) {
    holder.putDatabaseForTable(MyClass.class, this);
    models.add(MyClass.class);
    modelTableNames.put("MyClass", MyClass.class);
    modelAdapters.put(MyClass.class, new MyClass$Adapter(holder));
  }

```

And I get :
```
W/System.err: com.raizlabs.android.dbflow.structure.InvalidDBConfiguration: Table: fr.mypackage.MyClass is not registered with a Database. Did you forget the @Table annotation?
```

**Comment by levibostian** [comment]
I have some into as well. 

---

I created a copy of the generated `BaseDatabaseDefinition` file as well as the generated `DatabaseHolder` for when the app run great on the device and when it did not run successfully. 

I ran a diff between the two generated `BaseDatabaseDefinition` files and they are identical. **However** when I ran a diff between the two generated `DatabaseHolder` files, they are different. 

Here is their diff:
```
< import java.sql.Date;
> import java.util.Date;

<         typeConverters.put(Date.class, new SqlDateConverter());
<         typeConverters.put(java.util.Date.class, new DateConverter());
<         typeConverters.put(Boolean.class, new BooleanConverter());

>         typeConverters.put(Boolean.class, new BooleanConverter());
>         typeConverters.put(Date.class, new DateConverter());
>         typeConverters.put(java.sql.Date.class, new SqlDateConverter());
```

From this info, are the Date imports causing the issue? I did create a TypeConverter for dealing with dates:
```
package com.levibostian.db.typeconverters;

import com.raizlabs.android.dbflow.converter.TypeConverter;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

@com.raizlabs.android.dbflow.annotation.TypeConverter
public class DateConverter extends TypeConverter<String, Date> {

    @Override
    public String getDBValue(Date model) {
        SimpleDateFormat simpleDate =  new SimpleDateFormat("YYYY-MM-DD HH:MM:SS.SSS");

        return model == null ? null : simpleDate.format(model);
    }

    @Override
    public Date getModelValue(String data) {
        SimpleDateFormat simpleDate =  new SimpleDateFormat("YYYY-MM-DD HH:MM:SS.SSS");

        try {
            return data == null ? null : simpleDate.parse(data);
        } catch (ParseException e) {
            e.printStackTrace();

            return null;
        }
    }

}
```

As you can see, my typeconverter uses `import java.util.Date;` as an import. 

This is very interesting considering the fact that my *working* `DatabaseHolder` class actually uses `import java.sql.Date;` as an import?

Any help?

**Comment by mathieudebrito** [comment]
Personnally, I use joda datetime with custom converter. Also, I never got it working ( for the last 20 compilations, I always got the problem).

**Comment by mathieudebrito** [comment]
Ok, I launched my app in debug mode and tried to understand what's happening and here is what I found : 
```java
globalDatabaseHolder = {com.raizlabs.android.dbflow.config.FlowManager$GlobalDatabaseHolder@5661} 
 databaseClassLookupMap = {java.util.HashMap@5676}  size = 1
 databaseDefinitionMap = {java.util.HashMap@5677}  size = 11
  0 = {java.util.HashMap$HashMapEntry@5689} "class fr.myPackage.MyPlass" -> 
   key = {java.lang.Class@4958} "class fr.myPackage.MyPlass"
   value = {...}
...
```

So, in `DatabaseHolder`, 
```java
public DatabaseDefinition getDatabaseForTable(Class<? extends Model> table) {
    return databaseDefinitionMap.get(table);
}
```
returns null because of the `'class '` in front of the className. 
Why is `'class '` added to the className ? I use Java 7

**Comment by carmas123** [comment]
I've solved all problem with Kotlin:

for Date problem I use a custom converter:
```
class DateConverter : TypeConverter<Long, Date>() {
    override fun getModelValue(data: Long?): Date? {
        if (data == null)
            return null
        else
            return Date(data)
    }

    override fun getDBValue(model: Date?): Long? = model?.time

}

```
and using typeConverter = DateConverter::class for all Date colum in my models.

for DatabaseHolder I solved with this (because sometimes ???) I got the "Table is not registered with a Database"

Create a custom DatabaseHolder
```
class IMDatabaseHolder() : DatabaseHolder() {

    init {
        // Initialize the Database Definition
        DBLocalDBLocal_Database(this)
    }
}
```

done now all work fine

**Comment by agrosner** [comment]
It appears this is a bug with incremental compilation. If you use `kapt` even if you specify:
```groovy
dexOptions.incremental = false
```
Kotlin seems to ignore this and still send DBFlow only changed classes, causing generated files not to generate. 

Also ensure incremental compilation is off if you're using java. There is much better messaging in `develop`, but I've seen this kind of question appearing in other annotation processors.

**Comment by levibostian** [comment]
@agrosner I am not using Kotlin. Does that effect me? 

@carmas123 I don't understand your solution. How did you create that database holder? 

@mathieudebrito I tried your solution even though I am not using ProGuard. No luck.

---

I am happy to hear the solutions on this page are seeming to help others. I am however not using Kotlin or ProGuard and still having the issue. That makes me think these solutions above are temporary and may not work 100% of the time and not the solution to the root problem.

**Comment by agrosner** [comment]
@levibostian simple question have you tried using the `FlowConfig.Builder`'s method `openDatabasesOnInit()` to see if this fixes your race condition issue?

**Comment by agrosner** [comment]
`mFlowCursorList = new FlowCursorList<UserModel>(false, SQLite.select().from(UserModel.class).where(UserModel_Table.responded.isNull()).orderBy(UserModel_Table.user_id, true));
`

**Comment by agrosner** [comment]
@levibostian strange, are you sure incremental compilation is off

**Comment by agrosner** [comment]
Also @carmas123 solution would work nicely if you don't make table changes. If you make any kind of changes to dbflow classes, you would need to do a full rebuild.

**Comment by levibostian** [comment]
Hmmmm... I am not sure if I have incremental builds on? I have instant run off for sure as another issue here listed that as the solution. 

I did assume that when I changed any dbflow classes I would have to do a full rebuild. That makes sense. But as you know from my description of the issue above, that is not the case. A couple times I will comment out one line of code in my activity that is not involved with dbflow and it fails.

**Comment by agrosner** [comment]
@levibostian try adding:
```
dexOptions.incremental = false

```
to your android block

**Comment by levibostian** [comment]
@agrosner I just added `dexOptions.incremental = false` to my android block, did a gradle clean, fresh install on my device, and crashed first try.

**Comment by pshingala** [comment]
dagger 2.2
retrofit 2.0.2
dbflow 3.0.0-beta6
eventbus:3.0.0
gradle 2.1.0
android studio 2.1.1 & 1.5.x

@agrosner I tried everything from this thread as well as from other related threads, yet randomness persists!

**Comment by levibostian** [comment]
Thank you @pshingala for chiming in. Glad to hear it's more then just me. 

At first, I thought it was Dagger interfering with DBFlow while generating code but I have a couple projects that don't use Dagger at all and it still happens. 

I have worked with a few projects. 1 that doesn't use Dagger, Retrofit, Eventbus, or anything else and issue still persists.

**Comment by joxad** [comment]
Hi, I got this problem also using only Kotlin on a fresh new app (no dagger or anything)...

FlowManager is created in the App (present in the manifest)
I have 2 model classes with @Table but it considers the table doesnt exist... 
I guess it is a problem of Kotlin for me, but @pshingala  got problem in java ..

**Comment by pshingala** [comment]
@joxad How do you explain that some times it worked?

@agrosner @levibostian The problem is gone after refactoring of the project. Removed unused imports, files etc. Also checked dbflow annotations, access modifiers of fields / methods etc.  Couldn't pin-point the reason for it!  However I strongly believe the error message was misleading and not helpful.

**Comment by joxad** [comment]
For me it fails every time if everything kotlin. I make it working this way :

Model class in java.
Application class in java.
The other classes in kotlin.

I tested this sample from jetbrain : https://github.com/JetBrains/kotlin-examples/tree/master/gradle/android-dbflow but it doesn't work

**Comment by trevjonez** [comment]
@agrosner I wonder if the changes I made in PR #850 might help with this. Before my changes i was left with `@Table` classes that lacked an accompanying `_Adapter` and `_Table` class as well as the generated `_Database` class missing constructor statements. And I just pushed another commit that will push the holder def off to the end as well.

**Comment by agrosner** [comment]
People I would attempt it again after @trevjonez PR and see if you _still_ have issues. Its on `develop` and is slated for `3.1.0` release.

**Comment by Ajay-Jadhao** [comment]
@agrosner I'm still facing issue on develop also. Im just blocked and could not even execute project. Please address issue ASAP.

**Comment by natangr** [comment]
Any updates on this issue?

**Comment by agrosner** [comment]
Havent noticed any issues on any of my projects including a brand new project I started a month ago.

**Comment by leandrogtcampos** [comment]
Hi. Check if you are missing this piece of code:

FlowManager.init(new FlowConfig.Builder(this).build());

If you are, you will get the same error message.

**Comment by Informaticore** [comment]
I am using DBFlow 3.1.1 without Dagger or Kotlin and I have the same issue. 
If I build the app from Android Studio and run it, everything looks fine, but if I build the release version, it crashes with that error.

Seems to be a problem with proguard, but I am not able to find the correct proguard rules.
@mathieudebrito you told something about proguard, but there are no rules?! Can you post them for me please?

**Comment by mathieudebrito** [comment]
Sure, All I have is :  
> -keep class * extends com.raizlabs.android.dbflow.config.DatabaseHolder { *; }

**Comment by Informaticore** [comment]
Okay, this was not working for me. Still got the error.
I will try now following:

-keep class * extends com.raizlabs.android.dbflow.config.DatabaseHolder { *; }
-keep class com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder
-keep class * extends com.raizlabs.android.dbflow.config.BaseDatabaseDefinition { *; }
-keep class xx.xxx.xxx.xxx.models.** { *; }

(xxx = packagename)

**Comment by agrosner** [comment]
you might as well keep all dbflow classes then...really all you need to keep is:
```
-keep class * extends com.raizlabs.android.dbflow.config.DatabaseHolder { *; }
```
I use that in my projects and it works perfectly. This is b/c the rest of the code is processed, generated pre proguard step. The generated database holder class is instantiated once via reflection and using that line will tell proguard to keep it, which in turn notices that the other classes are used and keeps all other ones, but allows them to be obfuscated.

**Comment by luizmello** [comment]
I was with this issue, but for me after change the Gradle "android-apt plugin" to the "annotationProcessor" , the problem gone.

**Comment by AdamSHurwitz** [comment]
Because I'm using Kotlin I switched `annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"` to use **kapt** and it fixed it.
